### ISSUE TITLE
Fix inter-chapter links

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#105]
In PR #95, we updated the chapter link syntax.
However the result is slightly off.
(I've cleared out and re-downloaded the new version of Pharo (4) and pillar, by running the download.sh script. Pulled a fresh copy of the repo. Compiled the book.)

`Chapter *: SUnit>../SUnit/SUnit.pillar@cha:sunit*` compiles into `Chapter : SUnit`.  Is there supposed to be a character that resolves into the chapter number, before the colon?
(cc @jecisc )

**Comment by jecisc** [comment]
Hum... Can you give me the chapter where you found that ? Because I see the number.
See at: https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/FirstApplication/FirstApplication.html

Inside the section `III.2. Creating a new Package` I see `Chapter 2 : A Quick Tour of Pharo`

(By the way, we will update the pillar.conf later to have a better numerotation an avoid to have something like III.2.C.a. etc...)

**Comment by dmitrizagidulin** [comment]
Ah, so it looks like it renders correctly in HTML, but not in PDF.
Take a look at that same link in https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/FirstApplication/FirstApplication.pdf

**Comment by jecisc** [comment]
Oh yes, I didn't saw it.
LaTeX use his own numerating system. In HTML Pillar manage it but in LaTeX it's not Pillar.

But two things.

First you will never have a numerotation in individual PDF because LaTeX doesn't manage inter-file links. It's for that we want always an alias on an inter-file link: to not have something to render when we don't have a number with a link. A solution would be to disable the LaTeX numerator and use our own numerator but it's a lot of work, I don't have the time to do it now.

Second, I agree that in the book result we should have the chapter number... But it's LaTeX which manage his numbers. On the inter-chapter links we used \hyperref[anchorAtTheBeginningOfTheChapter]{Alias}. Do you know a way in LaTeX to create a link to an anchor that will render the number AND the Alias ?
If LaTeX doesn't do that we'll need to do it in Pillar.

**Comment by jecisc** [comment]
I'll add this correction on my TODO list and add it on the next version of Pillar.

**Comment by dmitrizagidulin** [comment]
@jecisc - I don't know if LaTeX has any way to render both the number AND alias. (I'm not that familiar with it).

But - is there any way we can have a Pillar link syntax that resolves to the chapter number, AND a different notation that resolves to a link (like the chapters currently do)?

Before, when we didn't have the inter-file link capability, we just used links that resolved to chapter number: `Chapter *cha:tour*: A Quick Tour of Pharo`, so only the chapter number was hyper-linked (and the chapter name/alias was not linked). 

Now, we have gained the inter-file link ability (so the whole chapter name is linked), but lost the chapter number. It would be great to have both, something like `Chapter *#number>@cha:sunit*: *SUnit>../SUnit/SUnit.pillar@cha:sunit*` that would render as: `Chapter 9: SUnit`, with both `9` and `SUnit` hyper-linked (separately, if necessary).

Until we have the ability to do both kinds of links (a number and an alias), we need to fix our chapter references to:

`Chapter 9: *SUnit>../SUnit/SUnit.pillar@cha:sunit*` (so that we hardcode out the chapter number in the text, and only the alias (SUnit, here) will be hyperlinked). Does that make sense?

**Comment by jecisc** [comment]
On the next stable version of Pillar (and on the development version now) the current syntax works. 
This is an example of the book with the current syntax and the development version of Pillar: http://puu.sh/iJtGX/5f865c1374.png.

I will close the issue with the next release of Pillar.

**Comment by dmitrizagidulin** [comment]
Excellent! That's fantastic news. (One minor thing - can we get rid of the space after the chapter number and before the colon?)

**Comment by jecisc** [comment]
Yes! Sorry I have the habits of the French conventions and in French we have to put a space between a number and a colon. I will remove this space and the French people will have to add the space in the Alias of the link.

**Comment by dmitrizagidulin** [comment]
Interesting, didn't know that! :)

**Comment by dmitrizagidulin** [comment]
Closing, this has been fixed. (Inter-chapter links are now working, thanks Cyril!)

**Comment by kilon** [comment]
great work guys :)

**Comment by jecisc** [comment]
You're welcome :)
