### ISSUE TITLE
PharoTour - Remove icons list section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#140]
We need to remove (or, at very least, move to the Environment chapter) the figure and paragraph listing the available icons on a browser, at [PharoTour.pillar#L409-L422](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/PharoTour/PharoTour.pillar#L409-L422).
![pharobrowsericons](https://cloud.githubusercontent.com/assets/947005/10865596/948263ce-7fe6-11e5-81d7-d8248de58f11.png)

For several reasons:
1. The section doesn't belong in Pharo Tour, if it should be included at all, it should be in the Environment chapter.
2. More importantly -- it describes only _one_ particular Icon Set. Since icon sets are likely to change (or if users are using a different set), it becomes prohibitive to describe each set. 
3. The individual concepts are generally described in the sections they're introduced (for example, the method inheritance arrows are described in the sections discussing overriding and inheritance)
4. The format (lumping all the icons into one image, and then simply listing them from left to right) is not encountered elsewhere in the book, and in general clashes with the book's purpose (a By Example introduction, not a reference book).

**Comment by kilon** [comment]
Thats the standard icon set for Pharo 4 and Pharo 5 which is what UPBE supports. 

Icons play a vital role in understanding the role of classes and methods inside Nautilus, without the understanding of icons, the user misses a very important Nautilus feature. 

Furthermore the icons act also as buttons playing a vital role into the navigation of methods and classes inside System Browser a fundamental workflow for every pharo coder expert or a beginner. 

The cost of keep the icons is low compared to the benefit documenting them. Morever the purpose of the book is to keep everything up to date and document it as well as possible for the convenience of the reader and NOT the convenience of this book's editors. 

You cannot have a reference book for an IDE because a reference is about information that may or may not be used and should be read in any way and form that suits the reader. On the other hand tutorials explain information that is basic and foremost needed to the every day workflow and because IDEs are made to be used in it fullest they dont fit in a reference doc and so do not the description of their icons. 

I strongly disagree in the removal of icons and we should not forget that their addition was after a request from a begineer Pharoer. 

Moving the icons to the Enviroment chapter is not something I object.

**Comment by nicolaihess** [comment]
There is no reference to this image anymore. I close this issue.
