### ISSUE TITLE
BasicClasses - Are Points still self-evaulating?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#64]
In BasicClasses, in the [A word about representation and self-evaluating representation.](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/f0b13888e759a6fb0d214699e27b87a270d35697/BasicClasses/BasicClasses.pier#L93) section,
we mention that Points are self evaluating:
```
3@4       --> (3@4)
{10@10. 100@100}           --> {(10@10). (100@100)}
```
It sounds like the parentheses are new-ish (added after the chapter was originally written).

So, two questions:
1) Do points (with parentheses) still count as self-evaluating?
2) More importantly, why is the concept of _self-evaluating objects_ relevant to new developers? Can we just remove this section?

**Comment by Ducasse** [comment]
1) yes because we just reexcute the expression.
2) if you want but this is idea of self representation is nice because without it you would print a collection of points and you would get a collection of numbers and you cannot reproduce the collection of point in the workspace once you did a printString on the first collection 
Here you always can.

**Comment by Ducasse** [comment]
I reread the section and it is nice so I would keep it.
Many people do not get that Color red is an object printed as an expression that creates the Color red object

**Comment by dmitrizagidulin** [comment]
Thanks @Ducasse! I agree with your point, let's keep the section.
