### ISSUE TITLE
PharoObjectModel - question about Class instance variables

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#74]
Couple of questions about the Class instance variables section.

1. On [line 287](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/1b92947214f0275cf93bc23929ca079dd7269f67/PharoObjectModel/PharoObjectModel.pier#L287), we give an example of overriding the `new` method of the Dog class:

    ```
Dog class>>>new
    count := count +1.
    ^ super new
    ```
    Should we put in a brief warning that `new` is not usually overriden, in Pharo? (That it's used in rare cases like singleton creation). So that readers don't get the wrong idea that they should keep overriding `new`.

2. In the code snippet on [line 298](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/1b92947214f0275cf93bc23929ca079dd7269f67/PharoObjectModel/PharoObjectModel.pier#L298), we call `initialize` on the Dog and Hyena class.

    ```
Dog initialize.
Hyena initialize.
Dog count     --> 0
Hyena count --> 0
    ```
    Does this mean that you can't access (initialized) class instance variables unless you explicitly call `SomeClass initialize`? And if so, should we direct the readers' attention to this?

(cc @Ducasse and @DamienCassou )

**Comment by Ducasse** [comment]
basicNew should never never never be overriden but there is no problem to override new.
Class instance variables are just instance variables of the class (similar to instance varibales are instance variables of an instance). So we cannot access class instance variable from instance side or from the outside because there are protected (in Java parlance). To access class instance variable you have to have setter on the class side. 
Now there is nothing about calling initialize.
Class side initialize method is just  a method that is called automatically when the class is loaded in memory. Here we just call the initialize method to initialize the class instance variable nothing more. 
We do it manually because when you define a class it is not loaded in memory from file so the loader does not call initialize so you have to do it to get the variables initialized.
Is it clear?

**Comment by dmitrizagidulin** [comment]
@Ducasse - Clear, thank you! :)
Closing issue.
